spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    url: 'jdbc:mysql://localhost:3306/auction?useUnicode=true&characterEncoding=UTF-8'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mvc:
    view:
      prefix: /
      suffix: .jsp
pagehelper:
  helper-dialect: mysql
  reasonable: true
        
